# Día 1 – Entender el problema y el dataset

Notebook de práctica para aprender **exploración inicial de datos con Pandas**.

En este notebook aprenderás a:
- Entender qué es Pandas
- Trabajar con **DataFrames y Series**
- Cargar datasets
- Realizar una **exploración inicial** de los datos

---

## Dataset del ejercicio

Para este ejercicio debes elegir **cualquier dataset público de Kaggle**:

👉 https://www.kaggle.com/datasets

Pasos:

1. Busca un dataset que te resulte interesante.
2. Descárgalo en formato **CSV**.
3. Colócalo en la misma carpeta que este notebook.
4. Cárgalo usando `read_csv()`.

Durante el notebook irás analizando ese dataset paso a paso.

Al final tendrás que crear **un pequeño reporte sobre el dataset**.

---
# 1. Introducción a Pandas

## Teoría

**Pandas** es una de las librerías más utilizadas en Python para:

- Análisis de datos
- Limpieza de datasets
- Transformación de datos
- Exploración inicial

Las dos estructuras principales de Pandas son:

### Series  → estructura de datos unidimensional. 
Para crear una serie El método más común es pasar una lista: 
```
s = pd.Series([1, 3, 5, 7])
```

### DataFrame  → tabla bidimensional (similar a Excel o SQL)
Para crear un dataframe es necesario pasar un diccionario:
```
df = pd.DataFrame({'Col1': [1, 2], 'Col2': ['a', 'b']})
```

Pandas permite trabajar con datos de forma muy eficiente.

### Ejercicios

1️⃣ Investiga qué versión de Pandas estás utilizando.

2️⃣ Crea una **Series simple** con 5 números.

3️⃣ Convierte esa Series en un DataFrame.

In [ ]:
pip install pandas

Collecting pandas
  Downloading pandas-2.3.3-cp310-cp310-win_amd64.whl (11.3 MB)
     ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
     ---- ----------------------------------- 1.1/11.3 MB 24.2 MB/s eta 0:00:01
     ----------------- ---------------------- 5.0/11.3 MB 63.5 MB/s eta 0:00:01
     -------------------------------------  11.3/11.3 MB 165.0 MB/s eta 0:00:01
     -------------------------------------- 11.3/11.3 MB 109.9 MB/s eta 0:00:00
Collecting tzdata>=2022.7
  Downloading tzdata-2025.3-py2.py3-none-any.whl (348 kB)
     ---------------------------------------- 0.0/348.5 kB ? eta -:--:--
     ---------------------------------------- 348.5/348.5 kB ? eta 0:00:00
Collecting pytz>=2020.1
  Downloading pytz-2026.1.post1-py2.py3-none-any.whl (510 kB)
     ---------------------------------------- 0.0/510.5 kB ? eta -:--:--
     ---------------------------------------- 510.5/510.5 kB ? eta 0:00:00
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\softwaregamevision\appdata\roaming\python\python310\site-packages (from pandas) (2.9.0.post0)
Collecting numpy>=1.22.4
  Downloading numpy-2.2.6-cp310-cp310-win_amd64.whl (12.9 MB)
     ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
     ------------------- ------------------- 6.6/12.9 MB 140.3 MB/s eta 0:00:01
     -------------------------------------  12.9/12.9 MB 162.4 MB/s eta 0:00:01
     -------------------------------------- 12.9/12.9 MB 108.7 MB/s eta 0:00:00
Requirement already satisfied: six>=1.5 in c:\users\softwaregamevision\appdata\roaming\python\python310\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Installing collected packages: pytz, tzdata, numpy, pandas
Successfully installed numpy-2.2.6 pandas-2.3.3 pytz-2026.1.post1 tzdata-2025.3
Note: you may need to restart the kernel to use updated packages.

  WARNING: The scripts f2py.exe and numpy-config.exe are installed in 'c:\Users\SoftwareGameVision\AppData\Local\Programs\Python\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 23.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
import pandas as pd
# Verificar versión
print(pd.__version__)

2.3.3

In [ ]:
df = serie.to_frame()

print(df)

    0
0  10
1  20
2  30
3  40

In [ ]:
import pandas as pd

serie = pd.Series([1, 2, 3, 4, 5])

print(serie)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
# Escribe aquí tus respuestas

# 1 Version De Panda 2.3.3 _ _ _ _ _

# 2  SERIE SIMPLE _ _ _ _ _ _ _ _ _ _
#    0    1
#    1    2
#    2    3
#    3    4
#    4    5
#    dtype: int64

# 3 DataFrame _ _ _ _ _ _ _ _ _ _ _ _ _

#   0
# 0  1
# 1  2
# 2  3
# 3  4
# 4  5

---
# 2. DataFrame

## Teoría

Un **DataFrame** es la estructura principal de Pandas.

Se puede imaginar como una **tabla**:

- Filas → observaciones
- Columnas → variables

Cada columna puede tener un tipo de dato distinto.

Los DataFrames permiten:

- Filtrar datos
- Agrupar datos
- Calcular estadísticas
- Transformar columnas

In [50]:
data = {
    "Nombre": ["Ana", "Luis", "Marta"],
    "Edad": [25, 30, 22],
    "Ciudad": ["Madrid", "Barcelona", "Valencia"]
}

df_ejemplo = pd.DataFrame(data)
df_ejemplo

  Nombre  Edad     Ciudad
0    Ana    25     Madrid
1   Luis    30  Barcelona
2  Marta    22   Valencia

### Ejercicios

1️⃣ Crear un DataFrame con al menos **3 columnas y 5 filas**.

2️⃣ Mostrar solo una de las columnas.

3️⃣ Mostrar solo las **dos primeras filas**.

In [54]:
# Escribe aquí tus respuestas

data = {
    
"Nombre": ["Tomb Rider", "Resident Evil", "Hell Blade" ],
"Empresa": ["Cristal Dynamic", "Capcom", "Ninja Teory"],
"Ciudad": ["Redwood City", "Tokyo", "Londres"],
"Año": [1996, 1997, 2017 ]
}

df_ejemplo = pd.DataFrame(data)
df_ejemplo

          Nombre          Empresa        Ciudad   Año
0     Tomb Rider  Cristal Dynamic  Redwood City  1996
1  Resident Evil           Capcom         Tokyo  1997
2     Hell Blade      Ninja Teory       Londres  2017

---
# 3. Series

## Teoría

Una **Series** es una estructura unidimensional de Pandas.

Es similar a una **columna de una tabla**.

Cada elemento tiene un valor y un índice.

In [46]:
serie = pd.Series([10, 20, 30, 40])
serie

0    10
1    20
2    30
3    40
dtype: int64

### Ejercicios

1️⃣ Crear una Series con los nombres de 5 ciudades.

2️⃣ Crear una Series con valores numéricos.

3️⃣ Mostrar el tercer elemento de la Series.

In [ ]:
# Escribe aquí tus respuestas

serie_De_Ciudades = pd.serie_De_Ciudades("Nueva York", "Londres", "París", "Tokio", "Zaragoza") 

serie_De_Ciudades = pd.serie_De_Ciudades([1, 2, 3, 4, 4])

---
# 4. Cargar datos con read_csv()

## Teoría

La función más utilizada para cargar datasets es:

`pd.read_csv()`

Permite cargar archivos CSV y convertirlos automáticamente en un DataFrame.

Ejemplo:

```python
df = pd.read_csv('dataset.csv')
```

In [ ]:
import os
os.listdir()

### Ejercicios

1️⃣ Cargar el dataset que descargaste de Kaggle.

2️⃣ Mostrar las primeras filas.

3️⃣ Guardar el DataFrame en una variable llamada `df`.

In [ ]:
# Escribe aquí tus respuestas

import pandas as pd

# 1 Cargar el dataset
df = pd.read_csv("indie-games-developers.csv")

# 2️ Mostrar las primeras filas
df.head()

,Developer,City,Autonomous area,Country,Notable games,Notes
0,11 bit studios,Warsaw,NaN,Poland,AnomalyThis War of MineFrostpunk,NaN
1,ACE Team,Santiago,Santiago,Chile,Zeno ClashRock of Ages,NaN
2,Akupara Games,Los Angeles,California,United States,Whispering Willows The Metronomicon: Slay the ...,NaN
3,Alec Holowka,Winnipeg,Manitoba,Canada,Crayon Physics DeluxeI'm O.K – A Murder Simula...,NaN
4,Alientrap,Saskatoon,Saskatchewan,Canada,CapsizedApotheon,NaN

---
# 5. Exploración inicial del dataset

## Teoría

Antes de analizar los datos es importante **explorar el dataset**.

Funciones clave:

`df.head()` → primeras filas

`df.info()` → tipos de datos y valores nulos

`df.describe()` → estadísticas

`df.shape` → tamaño del dataset

In [ ]:
df.head()

### Ejercicios

1️⃣ Mostrar las **primeras 10 filas**.

2️⃣ Mostrar la información del dataset (`info`).

3️⃣ Mostrar estadísticas descriptivas.

4️⃣ Mostrar el número de filas y columnas.

5️⃣ Identificar columnas con valores nulos.

In [4]:
# Escribe aquí tus respuesta

# 1️ primeras 10 filas
df.head(10)

# 2️ información del dataset
df.info()

# 3️ estadísticas descriptivas
df.describe()

# 4️ número de filas y columnas
df.shape

# 5️ columnas con valores nulos
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Developer        200 non-null    object
 1   City             185 non-null    object
 2   Autonomous area  107 non-null    object
 3   Country          200 non-null    object
 4   Notable games    192 non-null    object
 5   Notes            11 non-null     object
dtypes: object(6)
memory usage: 9.5+ KB

Developer            0
City                15
Autonomous area     93
Country              0
Notable games        8
Notes              189
dtype: int64

---
# Preguntas finales

Utilizando el dataset de Kaggle que elegiste, escribe un **reporte breve** que responda:

1️⃣ ¿De qué trata el dataset?

2️⃣ ¿Cuántas filas y columnas tiene?

3️⃣ ¿Qué variables contiene?

4️⃣ ¿Qué tipos de datos hay?

5️⃣ ¿Existen valores nulos?

6️⃣ ¿Qué primeras conclusiones puedes sacar?

Escribe tu análisis en una celda Markdown.

In [ ]:
# Escribe aquí tu reporte final

# 1️  ¿De qué trata el dataset?_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

# El dataset trata sobre desarrolladores de videojuegos independientes 
# y empresas relacionadas con este sector. Básicamente contiene información 
# sobre estudios o desarrolladores y en qué región se encuentran o trabajan dentro 
# de la industria del videojuego.

# 2 ¿Cuántas filas y columnas tiene?_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ __  _ _ _ _ _ _ _ _ _ _ _ _

# El dataset tiene X filas y X columnas, que he podido ver usando df.shape. 
# Esto indica la cantidad de registros que hay y cuántas variables diferentes contiene el dataset.

# 3 ¿Qué variables contiene?_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

# Las variables son las columnas del dataset. Entre ellas hay información 
# como el nombre del desarrollador o estudio, la región donde se encuentra 
# y otros datos relacionados con la industria del videojuego.

# 4 ¿Qué tipos de datos hay?_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

# En el dataset hay principalmente dos tipos de datos: object, que corresponde a texto (por ejemplo nombres o regiones).
# int64 o float64, que son datos numéricos. Esto se puede ver usando la función df.info().

# 5 ¿Existen valores nulos?_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

# Al revisar el dataset con df.isnull().sum() 
# se puede ver si hay columnas que tienen valores nulos o datos que faltan. 
# Dependiendo del dataset puede haber algunas columnas con datos faltantes 
# que habría que limpiar antes de hacer un análisis más profundo.

# 6 ¿Qué primeras conclusiones puedes sacar?_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

# Después de explorar el dataset se puede entender 
# mejor cómo están organizados los datos y qué tipo de información contiene. 
# También sirve para detectar si hay valores nulos o columnas que necesitan limpieza. 
# En general, el dataset parece útil para analizar cómo se distribuyen 
# los desarrolladores o empresas dentro de la industria de los videojuegos.